### ISSUE TITLE
rviz crashes due to invalid quaternion after Interactive Marker Server applyChanges to existing marker

### ISSUE THREAD

**Issue by cassinaj** [ros-visualization/rviz#1185]
Changes made to the interactive marker via InteractiveMarkerServer::insert() or InteractiveMarkerServer::clear() followed by InteractiveMarkerServer::applyChanges() cause rviz to crash. When changes are made to a marker, an invalid quaternion is passed to OGRE causing the crash. This doesn't seem to affect creating new markers, though. E.g. the crash happens when removing some or even all controllers of a marker and applying the changes resulting in the following server update on the /interactive_marker/update_full topic (both cases the server is not sending unnormalized quaternions):

Clearing server and apply changes:
```
server_id: "/particle_tracker"
seq_num: 2
markers: []
```
Removing a subset of controllers and apply changes:
```
server_id: /particle_tracker
seq_num: 2 
markers: 
  -
    header: 
      seq: 0
      stamp: 
        secs: 1516072361
        nsecs: 227513561
      frame_id: "camera_depth_optical_frame"
    pose: 
      position: 
        x: 0.0934688001871
        y: 0.127441003919
        z: 0.961609005928
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
    name: "0"
    description: "[inactive] Click to active"
    scale: 0.20000000298
    menu_entries: []
    controls: 
      - 
        name: "button_control"
        orientation: 
          x: 0.0
          y: 0.0
          z: 0.0
          w: 1.0
        orientation_mode: 0
        interaction_mode: 2
        always_visible: True
        markers: 
          - 
            header: 
              seq: 0
              stamp: 
                secs: 0
                nsecs:         0
              frame_id: ''
            ns: ''
            id: 0
            type: 10
            action: 0
            pose: 
              position: 
                x: 0.0
                y: 0.0
                z: 0.0
              orientation: 
                x: 0.0
                y: 0.0
                z: 0.0
                w: 1.0
            scale: 
              x: 1.0
              y: 1.0
              z: 1.0
            color: 
              r: 0.5
              g: 0.5
              b: 0.5
              a: 0.20000000298
            lifetime: 
              secs: 0
              nsecs:         0
            frame_locked: False
            points: []
            colors: []
            text: ''
            mesh_resource: "package://object_meshes/object_models/impact_battery.obj"
            mesh_use_embedded_materials: False
        independent_marker_orientation: False
        description: ''
```
