### ISSUE TITLE
LaserScan Display type does not display anything when the sensor has a single ray.

### ISSUE THREAD

**Issue by mihirk284** [ros-visualization/rviz#1541]
Hello,
I am using Rviz to visualize the data received from the Ignition Gazebo simulator for the SubT challenge. 
I have four individual single ray laser sensors on my robot modelled by "gpu_rays". 

When I configure my sensor to have a single ray, RViZ detects the message, however, there is no update in the visual on the screen. The single point is not visible. For example when my sensor properties are:-
```
<scan>
  <horizontal>
    <samples>1</samples>
    <resolution>1</resolution>
    <min_angle>0.0</min_angle>
    <max_angle>0.0</max_angle>
    </horizontal>
</scan>
```
There is no display of the sensor range data (compare with later image)

![image](https://user-images.githubusercontent.com/27280479/92652940-440b4300-f30b-11ea-9f3f-403cd93ac7bf.png)

The echoed message is:-
```
header: 
  seq: 1562
  stamp: 
    secs: 31
    nsecs: 252000000
  frame_id: "Mihir/base_link/front_right_laser"
angle_min: 0.0
angle_max: 0.0
angle_increment: nan
time_increment: 0.0
scan_time: 0.0
range_min: 0.019999999553
range_max: 80.0
ranges: [10.467548370361328]
intensities: [0.0]
```

However, it is visible when the sensor is configured to scan for more than 1 ray.
```
<scan>
  <horizontal>
    <samples>2</samples>
    <resolution>1</resolution>
    <min_angle>0.0</min_angle>
    <max_angle>0.000001</max_angle>
    </horizontal>
</scan>
```
This case displays the range value. As red flat-square in the top right corner of the image.
![image](https://user-images.githubusercontent.com/27280479/92653171-977d9100-f30b-11ea-94e2-c969b3cb9500.png)

The message, in this case, reads as:-
```
header: 
  seq: 2335
  stamp: 
    secs: 46
    nsecs: 712000000
  frame_id: "Mihir/base_link/front_right_laser"
angle_min: 0.0
angle_max: 9.99999997475e-07
angle_increment: 9.99999997475e-07
time_increment: 0.0
scan_time: 0.0
range_min: 0.019999999553
range_max: 80.0
ranges: [10.461502075195312, 10.479777336120605]
intensities: [0.0, 0.0]
```

Please do let me know if this is an issue or if I am doing something wrong on my end.

Thanks.

### My environment
* OS Version: Ubuntu 18.04
* ROS Distro: [Melodic]
* RViz, Qt, OGRE, OpenGl version as printed by rviz:

```
[ INFO] [1599684045.497670936]: rviz version 1.13.13
[ INFO] [1599684045.497702449]: compiled against Qt version 5.9.5
[ INFO] [1599684045.497709203]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1599684045.512165924]: Forcing OpenGl version 0.
[ INFO] [1599684046.517309004]: Stereo is NOT SUPPORTED
[ INFO] [1599684046.517375294]: OpenGl version: 4.6 (GLSL 4.6).
```
