### ISSUE TITLE
Incorrect TF transform

### ISSUE THREAD

**Issue by tsukione** [ros-visualization/rviz#1736]
There is a incorrect TF transform in a moment, 
![incorrect_tf_transform](https://user-images.githubusercontent.com/81400392/162386224-033bf704-6161-4c5a-b4a8-455462a4b20e.gif)

It could be reproduced by the rosbag and reproduce.rviz in the zip file

[incorrect_tf_transform.zip](https://github.com/ros-visualization/rviz/files/8449635/incorrect_tf_transform.zip)

I have checked the tf data frame by frame in rosbag, the data seems normal.

### Your environment
* OS Version: Ubuntu 18.04
* ROS Distro: Melodic
* RViz, Qt, OGRE, OpenGl version as printed by rviz:
```
[ INFO] [1649385616.809809680]: rviz version 1.13.24
[ INFO] [1649385616.809844552]: compiled against Qt version 5.9.5
[ INFO] [1649385616.809852359]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1649385616.812327294]: Forcing OpenGl version 0.
[ INFO] [1649385617.079630994]: Stereo is NOT SUPPORTED
```
* If source build, which git commit?
* System locale, i.e. the output of `echo "$LANG $LC_NUMERIC"`:
  Before reporting a rendering issue, try running RViz with `LANG=C rviz`!

**Comment by rhaschke** [comment]
Carefully monitoring the transform `map -> body` reveals that this transform changes orientation from time 1579178476.09 to 1579178476.19, resulting in the observed glitch:
```
    header: 
      seq: 6427
      stamp: 
        secs: 1579178476
        nsecs:  90714185
      frame_id: "/map"
    child_frame_id: "/body"
    transform: 
      translation: 
        x: 660.9413619666593
        y: -171.05490377591923
        z: 0.33
      rotation: 
        x: 0.004361930060409506
        y: 0.008665464901892255
        z: 0.7051528692946266
        w: 0.7089889380023765
```
```
    header: 
      seq: 6431
      stamp: 
        secs: 1579178476
        nsecs: 190715185
      frame_id: "/map"
    child_frame_id: "/body"
    transform: 
      translation: 
        x: 660.9240520694293
        y: -170.16853572428226
        z: 0.33
      rotation: 
        x: 0.009107668952394725
        y: 0.003738851780159613
        z: -3.405387255255412e-05
        w: 0.9999515339224964
```
